# Generated by Django 3.2.20 on 2024-06-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti1p3_tool_config', '0001_initial'),
        ('lti_1p3_provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_keys', models.JSONField(default=list, help_text='Allows tool to access these specific UsageKeys')),
                ('allowed_orgs', models.JSONField(default=list, help_text='Allows tools to access any content in these orgs')),
                ('tool', models.OneToOneField(help_text='The tool to gate', on_delete=django.db.models.deletion.CASCADE, related_name='launch_gate', to='lti1p3_tool_config.ltitool')),
            ],
        ),
    ]
