# Generated by Django 3.2.20 on 2024-08-08 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('lti1p3_tool_config', '0001_initial'),
        ('lti_1p3_provider', '0002_launchgate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchgate',
            name='allowed_keys',
            field=models.JSONField(blank=True, default=list, help_text='Allows tool to access these specific UsageKeys'),
        ),
        migrations.AlterField(
            model_name='launchgate',
            name='allowed_orgs',
            field=models.JSONField(blank=True, default=list, help_text='Allows tools to access any content in these orgs'),
        ),
        migrations.CreateModel(
            name='LtiToolOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_org', to='lti1p3_tool_config.ltitool')),
            ],
        ),
    ]
