# Generated by Django 3.2.20 on 2024-08-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
        ('lti1p3_tool_config', '0001_initial'),
        ('lti_1p3_provider', '0003_auto_20240808_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchgate',
            name='allowed_courses',
            field=models.JSONField(blank=True, default=list, help_text="Allows tool to access these specific CourseKey's"),
        ),
        migrations.CreateModel(
            name='LtiKeyOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_org', to='lti1p3_tool_config.ltitoolkey')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
    ]
