# Generated by Django 3.2.20 on 2025-01-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_1p3_provider', '0004_auto_20240822_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiprofile',
            name='email',
            field=models.CharField(default='', help_text='Email claim if provided', max_length=255, verbose_name='email'),
        ),
    ]
