# Generated by Django 4.2.19 on 2025-09-16 17:53

from django.db import migrations, models
import lti_1p3_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_1p3_provider', '0005_ltiprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchgate',
            name='block_filter',
            field=models.JSONField(blank=True, default=lti_1p3_provider.models.block_filter_default, help_text='Allow only these block types to be launched/deep linked with for anything not specified by the course_block_filter or org_block_filter. Must be a list of block types.', validators=[lti_1p3_provider.models.validate_block_filter]),
        ),
        migrations.AddField(
            model_name='launchgate',
            name='course_block_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Allow only these block types to be launched in these courses. Valid format: {course_key: [block_types], ...}. These courses will only display these block types when deep linking.', validators=[lti_1p3_provider.models.validate_course_block_filter]),
        ),
        migrations.AddField(
            model_name='launchgate',
            name='org_block_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Allow only these block types to be launched in these orgs. Valid format: {org_short_name: [block_types], ...}. These orgs will only display these block types when deep linking.', validators=[lti_1p3_provider.models.validate_org_block_filter]),
        ),
        migrations.AlterField(
            model_name='launchgate',
            name='allowed_courses',
            field=models.JSONField(blank=True, default=list, help_text='Allows tool to access any content in these specific courses', validators=[lti_1p3_provider.models.validate_course_keys]),
        ),
        migrations.AlterField(
            model_name='launchgate',
            name='allowed_keys',
            field=models.JSONField(blank=True, default=list, help_text='Allows tool to access these specific UsageKeys', validators=[lti_1p3_provider.models.validate_usage_keys]),
        ),
        migrations.AlterField(
            model_name='launchgate',
            name='allowed_orgs',
            field=models.JSONField(blank=True, default=list, help_text='Allows tools to access any content in these orgs', validators=[lti_1p3_provider.models.validate_allowed_orgs]),
        ),
    ]
