# Generated by Django 4.2.19 on 2025-10-07 19:02

from django.db import migrations, models
import lti_1p3_provider.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_1p3_provider', '0006_launchgate_block_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchgate',
            name='dl_content_filter_path',
            field=models.CharField(blank=True, default='', help_text='Dotted path to Callable to filter dl content. Must accept a pylti1p3 MessageLaunch and return a Callable that accepts an XBlock instance and returns bool (True = keep, False = filter out)', max_length=255, validators=[lti_1p3_provider.models.validate_dl_content_filter_callback]),
        ),
    ]
